# Generated by Django 5.1.6 on 2025-04-07 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="userbarcodesettings",
            old_name="barcode_status",
            new_name="barcode_pull",
        ),
        migrations.RemoveField(
            model_name="studentinformation",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="studentinformation",
            name="code_student_id",
        ),
        migrations.RemoveField(
            model_name="studentinformation",
            name="current_mobile_id_rand",
        ),
        migrations.RemoveField(
            model_name="studentinformation",
            name="mobile_id_rand_array",
        ),
        migrations.RemoveField(
            model_name="studentinformation",
            name="session",
        ),
        migrations.RemoveField(
            model_name="userbarcodesettings",
            name="static_barcode",
        ),
        migrations.AddField(
            model_name="userbarcodesettings",
            name="barcode_pull_dynamic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userbarcodesettings",
            name="timestamp_verification",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userbarcodesettings",
            name="server_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.TextField()),
                ("total_usage", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField()),
                ("session", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userbarcodesettings",
            name="barcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mobileid.barcode",
            ),
        ),
    ]
