# Generated by Django 5.1.6 on 2025-03-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookie", models.TextField()),
                ("unique_code", models.CharField(max_length=6, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
