# Generated by Django 5.1.6 on 2025-03-31 09:10

import mobileid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0002_studentinformation_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinformation",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=mobileid.models.user_directory_path
            ),
        ),
    ]
