# Generated by Django 5.1.6 on 2025-03-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0002_transfer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentinformation",
            old_name="section",
            new_name="session",
        ),
    ]
