# Generated by Django 5.1.6 on 2025-04-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobileid",
            "0002_rename_barcode_status_userbarcodesettings_barcode_pull_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbarcodesettings",
            name="barcode_pull_dynamic",
        ),
        migrations.AddField(
            model_name="userbarcodesettings",
            name="dynamic_barcode",
            field=models.BooleanField(default=True),
        ),
    ]
