# Generated by Django 5.1.6 on 2025-04-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0003_remove_userbarcodesettings_barcode_pull_dynamic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbarcodesettings",
            name="barcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mobileid.barcode",
            ),
        ),
    ]
