services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    environment:
      - WEBAUTHN_RP_ID=${WEBAUTHN_RP_ID:-example.com}
      - BACKEND_ORIGIN=${BACKEND_ORIGIN:-https://api.example.com}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://example.com}
    command: >
      bash -lc "python manage.py makemigrations --noinput && python manage.py migrate &&
                cd src && gunicorn mobileid.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --workers 3"
    ports:
      - "8000:8000"

