# Generated by Django 5.2 on 2025-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0003_passkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passkey",
            name="credential_id",
            field=models.CharField(max_length=191, unique=True),
        ),
    ]
