# Generated by Django 5.2 on 2025-07-25 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0004_alter_passkey_credential_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_profile_img",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded PNG of the user's 128*128 avatar. No data-URI prefix.",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(10000)],
                verbose_name="avatar (Base64)",
            ),
        ),
    ]
