# Generated by Django 5.2 on 2025-07-25 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0005_alter_userprofile_user_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
