# Generated by Django 5.2 on 2025-07-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0006_alter_userprofile_profile_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuickAction",
        ),
        migrations.RemoveField(
            model_name="userextendeddata",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserChangeLog",
        ),
        migrations.DeleteModel(
            name="UserExtendedData",
        ),
    ]
