# Generated by Django 5.2.11 on 2026-03-30 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminOneTimePass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pass_code", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin One-Time Password",
                "verbose_name_plural": "Admin One-Time Passwords",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view", "View"),
                            ("add", "Add"),
                            ("change", "Change"),
                            ("delete", "Delete"),
                            ("action", "Action"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        blank=True,
                        help_text="Model or resource being accessed",
                        max_length=200,
                    ),
                ),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the action",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Audit Log",
                "verbose_name_plural": "Admin Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="core_admina_user_id_36708f_idx"
                    ),
                    models.Index(
                        fields=["action"], name="core_admina_action_0ed87f_idx"
                    ),
                    models.Index(
                        fields=["success"], name="core_admina_success_11d5f7_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="core_admina_timesta_8f049f_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="core_admina_ip_addr_4e8ecf_idx"
                    ),
                ],
            },
        ),
    ]
