# Generated by Django 5.2 on 2025-08-25 09:10

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="time created"
                    ),
                ),
                (
                    "barcode_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("DynamicBarcode", "DynamicBarcode"),
                            ("Identification", "Identification"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=15,
                    ),
                ),
                ("barcode", models.CharField(max_length=120, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BarcodeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_usage", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.barcode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BarcodeUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("information_id", models.CharField(max_length=100)),
                (
                    "user_profile_img",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded PNG of the user's 128*128 avatar. No data-URI prefix.",
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(10000)],
                        verbose_name="avatar (Base64)",
                    ),
                ),
                ("user_cookies", models.TextField(blank=True, null=True)),
                (
                    "linked_barcode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="index.barcode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBarcodeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_verification", models.BooleanField(default=False)),
                (
                    "associate_user_profile_with_barcode",
                    models.BooleanField(default=False),
                ),
                (
                    "barcode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="index.barcode",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
