# Generated by Django 5.2.11 on 2026-03-30 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time created')),
                ('barcode_uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('share_with_others', models.BooleanField(default=False)),
                ('barcode_type', models.CharField(choices=[('DynamicBarcode', 'DynamicBarcode'), ('Identification', 'Identification'), ('Others', 'Others')], default='Others', max_length=15)),
                ('barcode', models.CharField(max_length=120, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BarcodePullSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_setting', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknow', 'Unknow')], default='Unknow', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usage', models.PositiveIntegerField(default=0)),
                ('total_usage_limit', models.PositiveIntegerField(default=0)),
                ('daily_usage_limit', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True, db_index=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.barcode')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('information_id', models.CharField(max_length=100)),
                ('user_profile_img', models.TextField(blank=True, help_text="Base64 encoded PNG of the user's 128*128 avatar. No data-URI prefix.", null=True, verbose_name='avatar (Base64)')),
                ('gender_barcode', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknow', 'Unknow')], default='Unknow', max_length=10)),
                ('linked_barcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.barcode')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time used')),
                ('barcode_used', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.barcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBarcodePullSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_setting', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=10)),
                ('gender_setting', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknow', 'Unknow')], default='Unknow', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBarcodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_user_profile_with_barcode', models.BooleanField(default=False)),
                ('scanner_detection_enabled', models.BooleanField(default=False)),
                ('prefer_front_camera', models.BooleanField(default=True)),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.barcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['user', 'barcode_type', '-time_created'], name='idx_barcode_user_type_created'),
        ),
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['barcode_type', 'share_with_others'], name='idx_barcode_type_shared'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['barcode_used', 'time_created'], name='idx_txn_barcode_created'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-time_created'], name='idx_txn_user_created'),
        ),
    ]
