# Generated by Django 5.2 on 2025-08-14 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barcode",
            name="session",
        ),
        migrations.RemoveField(
            model_name="userbarcodesettings",
            name="barcode_pull",
        ),
        migrations.AddField(
            model_name="userbarcodesettings",
            name="associate_user_profile_with_barcode",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BarcodeUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("information_id", models.CharField(max_length=100)),
                (
                    "user_profile_img",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded PNG of the user's 128*128 avatar. No data-URI prefix.",
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(10000)],
                        verbose_name="avatar (Base64)",
                    ),
                ),
                (
                    "linked_barcode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="index.barcode"
                    ),
                ),
            ],
        ),
    ]
