# Generated by Django 5.2 on 2025-09-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_barcode_share_with_others_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcodeusage",
            name="daily_usage_limit",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
