# Generated by Django 5.2 on 2025-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_remove_barcode_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_cookies", models.TextField()),
                ("transfer_code", models.CharField(max_length=100)),
                ("cache_data", models.JSONField(blank=True, default=dict, null=True)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
