# Generated by Django 4.2.11 on 2025-11-06 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("index", "0003_add_daily_usage_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcodeuserprofile",
            name="gender_barcode",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Unknow", "Unknow")],
                default="Unknow",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="barcodeuserprofile",
            name="user_profile_img",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded PNG of the user's 128*128 avatar. No data-URI prefix.",
                null=True,
                verbose_name="avatar (Base64)",
            ),
        ),
        migrations.CreateModel(
            name="BarcodePullSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender_setting",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Unknow", "Unknow"),
                        ],
                        default="Unknow",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
