# Generated by Django 4.2.11 on 2025-11-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_userbarcodepullsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbarcodesettings",
            name="prefer_front_camera",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userbarcodesettings",
            name="scanner_detection_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
