# Generated by Django 4.2.11 on 2025-11-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0006_scanner_detection_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barcodeuserprofile",
            name="user_cookies",
        ),
    ]
