# Generated by Django 4.2.11 on 2025-11-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0007_remove_barcodeuserprofile_user_cookies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbarcodesettings",
            name="server_verification",
        ),
    ]
