# Generated by Django 5.2.11 on 2026-03-30 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0008_remove_server_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcodeusage",
            name="last_used",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="barcode",
            index=models.Index(
                fields=["user", "barcode_type", "-time_created"],
                name="idx_barcode_user_type_created",
            ),
        ),
        migrations.AddIndex(
            model_name="barcode",
            index=models.Index(
                fields=["barcode_type", "share_with_others"],
                name="idx_barcode_type_shared",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["barcode_used", "time_created"], name="idx_txn_barcode_created"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-time_created"], name="idx_txn_user_created"
            ),
        ),
    ]
