# Generated by Django 5.2 on 2025-06-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- Check if the column exists before attempting to rename it
                SELECT CASE 
                    WHEN EXISTS (
                        SELECT 1 FROM pragma_table_info('mobileid_barcode') WHERE name='student_id'
                    ) 
                    THEN 'ALTER TABLE mobileid_barcode RENAME COLUMN student_id TO linked_id;'
                    ELSE 'SELECT 1;' -- Do nothing if the column doesn't exist
                END;
            """,
            reverse_sql="""
                -- Check if the column exists before attempting to rename it
                SELECT CASE 
                    WHEN EXISTS (
                        SELECT 1 FROM pragma_table_info('mobileid_barcode') WHERE name='linked_id'
                    ) 
                    THEN 'ALTER TABLE mobileid_barcode RENAME COLUMN linked_id TO student_id;'
                    ELSE 'SELECT 1;' -- Do nothing if the column doesn't exist
                END;
            """,
        ),
    ]
