# Generated by Django 5.2 on 2025-07-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0002_rename_student_id_to_linked_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
