# Generated by Django 5.2 on 2025-07-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0003_userprofile_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDashboardSettings",
        ),
    ]
