# Generated by Django 5.2 on 2025-07-15 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0004_delete_userdashboardsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="barcode",
            name="barcode_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="barcode_type",
            field=models.CharField(
                choices=[("DynamicBarcode", "DynamicBarcode"), ("Others", "Others")],
                default="Others",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_verification", models.BooleanField(default=False)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("School", "School"),
                            ("Student", "Student"),
                            ("Staff", "Staff"),
                        ],
                        default="Student",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBarcodeUsageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(default=None, null=True)),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobileid.barcode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
