# Generated by Django 5.2 on 2025-07-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0005_barcode_barcode_id_alter_barcode_barcode_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="account_verification",
        ),
    ]
