# Generated by Django 5.2 on 2025-07-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0006_remove_useraccount_account_verification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="barcode",
            old_name="barcode_id",
            new_name="barcode_uuid",
        ),
        migrations.RemoveField(
            model_name="barcode",
            name="linked_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="failed_login_attempts",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_locked",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="locked_until",
        ),
        migrations.AlterField(
            model_name="barcode",
            name="barcode",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="barcode_type",
            field=models.CharField(
                choices=[
                    ("DynamicBarcode", "DynamicBarcode"),
                    ("Identification", "Identification"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="account_type",
            field=models.CharField(
                choices=[("School", "School"), ("User", "User"), ("Staff", "Staff")],
                default="User",
                max_length=10,
            ),
        ),
    ]
