# Generated by Django 5.2 on 2025-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0007_rename_barcode_id_barcode_barcode_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcode",
            name="time_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
