# Generated by Django 5.2 on 2025-07-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0008_barcode_time_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="time created"
            ),
        ),
    ]
