# Generated by Django 5.2 on 2025-07-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0009_alter_barcode_time_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserBarcodeUsageHistory",
        ),
    ]
