# Generated by Django 5.2 on 2025-07-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobileid", "0010_delete_userbarcodeusagehistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbarcodesettings",
            name="timestamp_verification",
        ),
    ]
