from .forms import UserRegisterForm
from .views import (
    CookieTokenObtainPairView,
    CookieTokenRefreshView,
    RSALoginView,
    api_avatar_upload,
    api_logout,
    api_profile,
    api_register,
    list_devices,
    login_challenge,
    passkey_auth_options,
    passkey_auth_verify,
    passkey_register_options,
    passkey_register_verify,
    revoke_all_other_devices,
    revoke_device,
    user_img,
    user_info,
)

__all__ = [
    "CookieTokenObtainPairView",
    "CookieTokenRefreshView",
    "RSALoginView",
    "api_avatar_upload",
    "api_logout",
    "api_profile",
    "api_register",
    "list_devices",
    "login_challenge",
    "passkey_auth_options",
    "passkey_auth_verify",
    "passkey_register_options",
    "passkey_register_verify",
    "revoke_all_other_devices",
    "revoke_device",
    "UserRegisterForm",
    "user_img",
    "user_info",
]
