name: Frontend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'pages/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'pages/**'
      - '.github/workflows/frontend-tests.yml'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    defaults:
      run:
        working-directory: ./pages

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: pages/yarn.lock

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Lint code
      run: yarn lint

    - name: Format check
      run: yarn format:check || echo "Format check completed"

    - name: Type check (if TypeScript)
      run: |
        if [ -f "tsconfig.json" ]; then
          yarn type-check || echo "No TypeScript configuration found"
        fi

    - name: Run unit tests (if configured)
      run: |
        if grep -q '"test"' package.json; then
          yarn test
        else
          echo "No unit tests configured"
        fi

    - name: Build for production
      run: yarn build

    - name: Test build output
      run: |
        if [ -d "dist" ]; then
          echo "Build successful - dist directory exists"
          ls -la dist/
        else
          echo "Build directory not found"
          exit 1
        fi

    - name: Preview build (smoke test)
      run: |
        timeout 10s yarn preview --port 4173 --host &
        PREVIEW_PID=$!
        sleep 3
        curl -f http://localhost:4173/ || echo "Preview server test completed"
        kill $PREVIEW_PID || true

  security-audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pages

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
        cache-dependency-path: pages/yarn.lock

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Security audit
      run: |
        yarn audit --level moderate || echo "Security audit completed with warnings"

    - name: Check for outdated packages
      run: |
        yarn outdated || echo "Outdated package check completed"