# Generated by Django 5.2 on 2025-08-25 09:10

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("information_id", models.CharField(max_length=100)),
                (
                    "profile_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user_profile_img",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded PNG of the user's 128*128 avatar. No data-URI prefix.",  # noqa: E501
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(10000)],
                        verbose_name="avatar (Base64)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
