# Generated by Django 4.2.11 on 2025-11-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0002_passkeycredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_profile_img",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded PNG of the user's 128*128 avatar. No data-URI prefix.",
                null=True,
                verbose_name="avatar (Base64)",
            ),
        ),
    ]
