# Generated by Django 5.2.7 on 2025-11-15 20:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0004_failedloginattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSAKeyPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this key pair",
                        unique=True,
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="RSA public key in PEM format (BEGIN PUBLIC KEY...END PUBLIC KEY)"
                    ),
                ),
                (
                    "private_key",
                    models.TextField(
                        help_text="RSA private key in PEM format (BEGIN PRIVATE KEY...END PRIVATE KEY)"
                    ),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        choices=[(2048, "2048 bits"), (4096, "4096 bits")],
                        default=2048,
                        help_text="RSA key size in bits",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this key pair is currently active for encryption/decryption",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rotated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this key was rotated (deactivated)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "RSA Key Pair",
                "verbose_name_plural": "RSA Key Pairs",
                "db_table": "authn_rsa_keypair",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="loginauditlog",
            new_name="authn_login_usernam_3db403_idx",
            old_name="authn_logi_usernam_5bd831_idx",
        ),
        migrations.RenameIndex(
            model_name="loginauditlog",
            new_name="authn_login_created_db2868_idx",
            old_name="authn_logi_created_1cad83_idx",
        ),
    ]
