# Generated by Django 4.2.11 on 2025-11-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0006_login_audit_enhancements"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loginauditlog",
            index=models.Index(
                fields=["success"], name="authn_login_success_d86091_idx"
            ),
        ),
    ]
