# Generated by Django 4.2.11 on 2025-11-28 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authn", "0007_loginauditlog_authn_login_success_d86091_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessTokenBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(db_index=True, max_length=255, unique=True)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_access_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacklisted Access Token",
                "verbose_name_plural": "Blacklisted Access Tokens",
                "indexes": [
                    models.Index(fields=["jti"], name="authn_acces_jti_7753aa_idx"),
                    models.Index(
                        fields=["expires_at"], name="authn_acces_expires_755b0d_idx"
                    ),
                ],
            },
        ),
    ]
