# Generated by Django 5.2.11 on 2026-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0009_delete_passkeycredential"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RSAKeyPair",
        ),
        migrations.AlterField(
            model_name="failedloginattempt",
            name="locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
